export const emailHelp = 'Introduce tu email'
export const emailError = 'Email incorrecto'
export const passwordHelp = 'Introduce tu password'
export const passwordError = 'Password incorrecto'
export const passwordConfirmationHelp = 'Repite el password'
export const passwordConfirmationError = 'Los passwords no coinciden'
//Start.js, Login.js, RegisterUser.js, RegisterChef.js
export const enter = 'Entrar'
export const register = 'Registrame'
export const facebook = 'Facebook'
export const passwordOk = 'Bienvenido'
export const wrongPassword = 'Password incorrecto'
export const init = 'Iniciar sesión'
//Logout.js
export const logout = 'Has cerrado sesión correctamente'
//ChefAddButton.js
export const addChef = 'Añadir un cocinero'
export const editChef = 'Editar cocinero'
export const home = 'Volver'
export const origin = 'Cocina de'
//ChefForm.js
export const firstName1 = 'Nombre (*)'
export const firstName = 'Nombre'
export const lastName1 = 'Apellidos (*)'
export const lastName = 'Apellidos'
export const avatar1 = 'Foto (*)'
export const avatar = 'Foto'
export const email1 = 'Email (*)'
export const email = 'Email'
export const phone1 = 'Teléfono (*)'
export const phone = 'Teléfono'
export const country1 = 'Pais (*)'
export const country = 'Pais'
//AddChef.js, ChefsList.js
export const save = 'Restaurante dado de alta'
export const chefForm = 'Formulario de chefs'
export const addChefButton = 'Dar de alta'
export const cuisine = '. Cocina de'
export const emptyLabel = 'No hay chefs disponibles'
export const textAddButton = 'Añadir chef'